import { eq } from "drizzle-orm";

import { createEmployee, createTruck } from "@/app/actions/job-operations";
import { completeOnboarding } from "@/app/actions/onboarding";
import { IntakeTokenForm } from "@/components/intake-token-form";
import { db } from "@/db";
import { employee, office, truck } from "@/db/app-schema";
import { requireTenantRole } from "@/lib/tenant";

export default async function SettingsPage() {
  const { organization, profile } = await requireTenantRole(["owner", "admin"]);
  const [offices, employees, trucks] = await Promise.all([
    db.select().from(office).where(eq(office.organizationId, organization.id)),
    db.select().from(employee).where(eq(employee.organizationId, organization.id)).orderBy(employee.lastName, employee.firstName),
    db.select().from(truck).where(eq(truck.organizationId, organization.id)).orderBy(truck.unitNumber),
  ]);
  return <><header className="app-header"><div><p className="eyebrow">COMPANY SETUP</p><h1>{organization.name}</h1><p>Tenant identity, subscription, offices, modules, and import readiness.</p></div></header><section className="settings-grid"><article className="settings-card"><h2>Company</h2><dl><dt>Legal name</dt><dd>{profile?.legalName}</dd><dt>Tenant slug</dt><dd>{organization.slug}</dd><dt>Phone</dt><dd>{profile?.phone || "Not set"}</dd><dt>Location</dt><dd>{[profile?.city, profile?.state].filter(Boolean).join(", ") || "Not set"}</dd></dl></article><article className="settings-card"><h2>Subscription</h2><dl><dt>Status</dt><dd>{profile?.subscriptionStatus}</dd><dt>Tier</dt><dd>{profile?.subscriptionTier}</dd><dt>Enabled modules</dt><dd>{profile?.enabledModules.join(", ")}</dd></dl></article><article className="settings-card"><h2>Offices</h2>{offices.map((item) => <p key={item.id}><strong>{item.name}</strong><br />{[item.city, item.state].filter(Boolean).join(", ")}</p>)}</article><article className="settings-card"><h2>Employees</h2>{employees.map((item) => <p key={item.id}><strong>{item.firstName} {item.lastName}</strong><br />{item.role}{item.phone ? ` · ${item.phone}` : ""}</p>)}<form action={createEmployee} className="record-form"><div className="form-row"><input name="firstName" placeholder="First name" required /><input name="lastName" placeholder="Last name" required /></div><div className="form-row"><input name="role" placeholder="Role" defaultValue="mover" /><input name="phone" placeholder="Phone" /></div><input name="email" type="email" placeholder="Email" /><button className="secondary-button">Add employee</button></form></article><article className="settings-card"><h2>Trucks</h2>{trucks.map((item) => <p key={item.id}><strong>{item.unitNumber}</strong><br />{item.truckType}{item.capacity ? ` · ${item.capacity}` : ""}</p>)}<form action={createTruck} className="record-form"><div className="form-row"><input name="unitNumber" placeholder="Unit number" required /><input name="truckType" placeholder="Type" defaultValue="moving truck" /></div><input name="capacity" placeholder="Capacity / notes" /><button className="secondary-button">Add truck</button></form></article><article className="settings-card"><h2>Automated lead intake</h2><p>Use a token to post JSON leads from a website form, partner, or email automation to <code>/api/intake/leads</code>.</p><IntakeTokenForm /></article><article className="settings-card"><h2>Legacy data</h2><p>No backup is required to operate the new system. A future SQL backup can be imported through reserved legacy IDs and auditable import batches.</p></article></section>{!profile?.onboardingCompletedAt && <form action={completeOnboarding}><button className="primary-button">Mark initial setup complete</button></form>}</>;
}
