import { and, desc, eq } from "drizzle-orm";
import Link from "next/link";
import { notFound } from "next/navigation";

import { addJobPayment, addStorageItem, assignCrew, assignEmployee, assignTruck, createCrew, createStorageRecord, saveJobContract } from "@/app/actions/job-operations";
import { updateJob } from "@/app/actions/jobs";
import { db } from "@/db";
import { crew, customer, employee, job, jobContract, jobCrewAssignment, jobEmployeeAssignment, jobPayment, jobTruckAssignment, storageItem, storageRecord, truck } from "@/db/app-schema";
import { requireTenant } from "@/lib/tenant";

export default async function JobDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const tenant = await requireTenant();
  const { id } = await params;
  const [record, crews, employees, trucks, assignments, employeeAssignments, truckAssignments, contract, payments, storage] = await Promise.all([
    db.select({ job, customer }).from(job).leftJoin(customer, eq(job.customerId, customer.id)).where(and(eq(job.id, id), eq(job.organizationId, tenant.organization.id))).limit(1),
    db.select().from(crew).where(and(eq(crew.organizationId, tenant.organization.id), eq(crew.active, true))).orderBy(crew.name),
    db.select().from(employee).where(and(eq(employee.organizationId, tenant.organization.id), eq(employee.active, true))).orderBy(employee.lastName, employee.firstName),
    db.select().from(truck).where(and(eq(truck.organizationId, tenant.organization.id), eq(truck.active, true))).orderBy(truck.unitNumber),
    db.select({ id: jobCrewAssignment.id, role: jobCrewAssignment.role, crewName: crew.name, leaderName: crew.leaderName }).from(jobCrewAssignment).innerJoin(crew, eq(jobCrewAssignment.crewId, crew.id)).where(and(eq(jobCrewAssignment.jobId, id), eq(jobCrewAssignment.organizationId, tenant.organization.id))),
    db.select({ id: jobEmployeeAssignment.id, role: jobEmployeeAssignment.role, firstName: employee.firstName, lastName: employee.lastName }).from(jobEmployeeAssignment).innerJoin(employee, eq(jobEmployeeAssignment.employeeId, employee.id)).where(and(eq(jobEmployeeAssignment.jobId, id), eq(jobEmployeeAssignment.organizationId, tenant.organization.id))),
    db.select({ id: jobTruckAssignment.id, role: jobTruckAssignment.role, unitNumber: truck.unitNumber, truckType: truck.truckType }).from(jobTruckAssignment).innerJoin(truck, eq(jobTruckAssignment.truckId, truck.id)).where(and(eq(jobTruckAssignment.jobId, id), eq(jobTruckAssignment.organizationId, tenant.organization.id))),
    db.select().from(jobContract).where(and(eq(jobContract.jobId, id), eq(jobContract.organizationId, tenant.organization.id))).limit(1),
    db.select().from(jobPayment).where(and(eq(jobPayment.jobId, id), eq(jobPayment.organizationId, tenant.organization.id))).orderBy(desc(jobPayment.createdAt)),
    db.select().from(storageRecord).where(and(eq(storageRecord.jobId, id), eq(storageRecord.organizationId, tenant.organization.id))).orderBy(desc(storageRecord.createdAt)),
  ]);
  if (!record[0]) notFound();
  const item = record[0].job;
  const person = record[0].customer;
  const contractRecord = contract[0];
  const paymentsTotal = payments.reduce((total, payment) => total + (payment.status === "paid" ? Number(payment.amount) : 0), 0);
  const storedItems = storage.length ? await db.select().from(storageItem).where(and(eq(storageItem.storageRecordId, storage[0].id), eq(storageItem.organizationId, tenant.organization.id))) : [];
  const dateValue = (value: Date | null) => value ? new Date(value).toISOString().slice(0, 16) : "";

  return <>
    <header className="app-header"><div><p className="eyebrow">JOB OPERATIONS</p><h1>{item.jobNumber}</h1><p>{person?.companyName || [person?.firstName, person?.lastName].filter(Boolean).join(" ") || "Unassigned customer"} · {item.status.replace("_", " ")}</p></div><div className="platform-actions"><Link className="secondary-button" href={`/app/jobs/${item.id}/dispatch`}>Dispatch</Link><Link className="secondary-button" href={`/app/jobs/${item.id}/records`}>Job activity</Link><Link className="secondary-button" href={`/app/jobs/${item.id}/storage`}>Storage</Link><Link className="secondary-button" href={`/app/jobs/${item.id}/billing`}>Billing</Link></div></header>
    <div className="operations-grid">
      <section className="workspace-panel"><p className="eyebrow">JOB CONTROL</p><h2>Schedule and dispatch details</h2><form action={updateJob} className="record-form"><input type="hidden" name="id" value={item.id} /><label>Status<select name="status" defaultValue={item.status}><option value="scheduled">scheduled</option><option value="dispatched">dispatched</option><option value="in_progress">in progress</option><option value="completed">completed</option><option value="cancelled">cancelled</option></select></label><div className="form-row"><label>Scheduled start<input name="scheduledStart" type="datetime-local" defaultValue={dateValue(item.scheduledStart)} /></label><label>Scheduled end<input name="scheduledEnd" type="datetime-local" defaultValue={dateValue(item.scheduledEnd)} /></label></div><div className="form-row"><label>Actual start<input name="actualStart" type="datetime-local" defaultValue={dateValue(item.actualStart)} /></label><label>Actual end<input name="actualEnd" type="datetime-local" defaultValue={dateValue(item.actualEnd)} /></label></div><div className="form-row"><label>Crew count<input name="crewCount" type="number" min="0" max="100" defaultValue={item.crewCount} /></label><label>Truck count<input name="truckCount" type="number" min="0" max="100" defaultValue={item.truckCount} /></label></div><label>Origin address<input name="originAddress" defaultValue={item.originAddress || ""} /></label><label>Destination address<input name="destinationAddress" defaultValue={item.destinationAddress || ""} /></label><label>Dispatch notes<textarea name="dispatchNotes" rows={4} defaultValue={item.dispatchNotes || ""} /></label><button className="primary-button">Save job details</button></form></section>
      <section className="workspace-panel"><p className="eyebrow">DISPATCH</p><h2>Crew assignments</h2>{assignments.length ? <div className="record-list">{assignments.map((assignment) => <div className="record-card" key={assignment.id}><strong>{assignment.crewName}</strong><span>{assignment.leaderName || "No leader listed"} · {assignment.role}</span></div>)}</div> : <p className="panel-intro">No crews assigned yet.</p>}<form action={assignCrew} className="record-form"><input type="hidden" name="jobId" value={item.id} /><div className="form-row"><label>Crew<select name="crewId" required><option value="">Select crew</option>{crews.map((crewItem) => <option key={crewItem.id} value={crewItem.id}>{crewItem.name}</option>)}</select></label><label>Role<input name="role" defaultValue="assigned" /></label></div><button className="secondary-button">Assign crew</button></form><form action={createCrew} className="record-form inline-form"><p className="eyebrow">NEW CREW</p><div className="form-row"><input name="name" placeholder="Crew name" required /><input name="leaderName" placeholder="Crew leader" /><button className="secondary-button">Create crew</button></div></form></section>
      <section className="workspace-panel"><p className="eyebrow">RESOURCES</p><h2>Employees and trucks</h2>{employeeAssignments.length ? <div className="record-list">{employeeAssignments.map((assignment) => <div className="record-card" key={assignment.id}><strong>{assignment.firstName} {assignment.lastName}</strong><span>{assignment.role}</span></div>)}</div> : <p className="panel-intro">No employees assigned yet.</p>}{truckAssignments.length ? <div className="record-list">{truckAssignments.map((assignment) => <div className="record-card" key={assignment.id}><strong>{assignment.unitNumber}</strong><span>{assignment.truckType} · {assignment.role}</span></div>)}</div> : <p className="panel-intro">No trucks assigned yet.</p>}<form action={assignEmployee} className="record-form"><input type="hidden" name="jobId" value={item.id} /><div className="form-row"><label>Employee<select name="employeeId" required><option value="">Select employee</option>{employees.map((employeeItem) => <option key={employeeItem.id} value={employeeItem.id}>{employeeItem.firstName} {employeeItem.lastName} · {employeeItem.role}</option>)}</select></label><label>Role<input name="role" defaultValue="mover" /></label></div><button className="secondary-button">Assign employee</button></form><form action={assignTruck} className="record-form"><input type="hidden" name="jobId" value={item.id} /><div className="form-row"><label>Truck<select name="truckId" required><option value="">Select truck</option>{trucks.map((truckItem) => <option key={truckItem.id} value={truckItem.id}>{truckItem.unitNumber} · {truckItem.truckType}</option>)}</select></label><label>Role<input name="role" defaultValue="primary" /></label></div><button className="secondary-button">Assign truck</button></form></section>
      <section className="workspace-panel"><p className="eyebrow">CONTRACT</p><h2>{contractRecord?.status || "pending"}</h2><form action={saveJobContract} className="record-form"><input type="hidden" name="jobId" value={item.id} /><label>Status<select name="status" defaultValue={contractRecord?.status || "pending"}><option>pending</option><option>sent</option><option>signed</option><option>declined</option></select></label><label>Document URL<input name="documentUrl" type="url" defaultValue={contractRecord?.documentUrl || ""} placeholder="https://..." /></label><label>Terms / contract notes<textarea name="terms" rows={5} defaultValue={String((contractRecord?.termsSnapshot as { terms?: string } | null)?.terms || "")} /></label><button className="secondary-button">Save contract status</button></form></section>
      <section className="workspace-panel"><p className="eyebrow">PAYMENTS</p><h2>${paymentsTotal.toFixed(2)} collected</h2>{payments.map((payment) => <p className="record-notes" key={payment.id}><strong>${Number(payment.amount).toFixed(2)}</strong> · {payment.status} · {payment.method} {payment.reference ? `· ${payment.reference}` : ""}</p>)}<form action={addJobPayment} className="record-form"><input type="hidden" name="jobId" value={item.id} /><div className="form-row"><label>Amount<input name="amount" type="number" min="0.01" step="0.01" required /></label><label>Method<select name="method"><option>card</option><option>cash</option><option>check</option><option>ach</option><option>unrecorded</option></select></label></div><div className="form-row"><label>Status<select name="status"><option>pending</option><option>authorized</option><option>paid</option><option>refunded</option><option>void</option></select></label><label>Reference<input name="reference" /></label></div><button className="secondary-button">Record payment</button></form></section>
      <section className="workspace-panel"><p className="eyebrow">STORAGE</p><h2>{storage.length} storage records</h2>{storage.map((storageRecordItem) => <div className="record-card" key={storageRecordItem.id}><strong>{storageRecordItem.location || "Unassigned location"}</strong><span>${Number(storageRecordItem.monthlyRate).toFixed(2)} / month</span>{storedItems.map((storedItem) => <small key={storedItem.id}>{storedItem.quantity} × {storedItem.description} {storedItem.barcode ? `· ${storedItem.barcode}` : ""}</small>)}<form action={addStorageItem} className="record-form inline-form"><input type="hidden" name="jobId" value={item.id} /><input type="hidden" name="storageRecordId" value={storageRecordItem.id} /><div className="form-row"><input name="description" placeholder="Stored item" required /><input name="quantity" type="number" min="1" defaultValue="1" /><input name="condition" placeholder="Condition" /><input name="barcode" placeholder="Barcode" /><button className="secondary-button">Add item</button></div></form></div>)}<form action={createStorageRecord} className="record-form"><input type="hidden" name="jobId" value={item.id} /><div className="form-row"><label>Location<input name="location" placeholder="Warehouse A / Bay 4" /></label><label>Monthly rate<input name="monthlyRate" type="number" min="0" step="0.01" defaultValue="0" /></label></div><label>Notes<textarea name="notes" rows={3} /></label><button className="secondary-button">Open storage record</button></form></section>
    </div>
  </>;
}
