import { desc, eq } from "drizzle-orm";
import Link from "next/link";

import { createJob, updateJobStatus } from "@/app/actions/jobs";
import { db } from "@/db";
import { customer, job, quote } from "@/db/app-schema";
import { requireTenant } from "@/lib/tenant";

const statuses = ["scheduled", "dispatched", "in_progress", "completed", "cancelled"] as const;

export async function JobsWorkspace() {
  const tenant = await requireTenant();
  const [records, quotes] = await Promise.all([
    db.select({ id: job.id, jobNumber: job.jobNumber, status: job.status, scheduledStart: job.scheduledStart, scheduledEnd: job.scheduledEnd, crewCount: job.crewCount, truckCount: job.truckCount, originAddress: job.originAddress, destinationAddress: job.destinationAddress, customerName: customer.companyName, firstName: customer.firstName, lastName: customer.lastName }).from(job).leftJoin(customer, eq(job.customerId, customer.id)).where(eq(job.organizationId, tenant.organization.id)).orderBy(desc(job.scheduledStart), desc(job.createdAt)).limit(200),
    db.select({ id: quote.id, quoteNumber: quote.quoteNumber, customerName: customer.companyName, firstName: customer.firstName, lastName: customer.lastName }).from(quote).leftJoin(customer, eq(quote.customerId, customer.id)).where(eq(quote.organizationId, tenant.organization.id)).orderBy(desc(quote.createdAt)).limit(200),
  ]);
  return <><header className="app-header"><div><p className="eyebrow">OPERATIONS</p><h1>Jobs &amp; scheduling</h1><p>Turn accepted estimates into scheduled move work and track the operational handoff.</p></div></header><div className="workspace-grid"><section className="workspace-panel"><p className="eyebrow">SCHEDULE</p><h2>{records.length} jobs</h2>{records.length === 0 ? <div className="inline-empty"><h3>No scheduled jobs</h3><p>Create one from an existing quote.</p></div> : <div className="record-list">{records.map((item) => <article className="record-card" key={item.id}><div className="record-summary"><div><span className={`status-pill status-${item.status}`}>{item.status.replace("_", " ")}</span><h3><Link href={`/app/jobs/${item.id}`}>{item.jobNumber}</Link></h3><p>{item.customerName || [item.firstName, item.lastName].filter(Boolean).join(" ") || "Unassigned customer"}</p></div><div className="record-meta"><span>{item.scheduledStart ? new Intl.DateTimeFormat("en-US", { dateStyle: "medium", timeStyle: "short" }).format(item.scheduledStart) : "Unscheduled"}</span><small>{item.crewCount} crew · {item.truckCount} trucks</small></div></div><p className="record-notes">{[item.originAddress, item.destinationAddress].filter(Boolean).join(" → ") || "Addresses pending"}</p><form className="record-actions" action={updateJobStatus}><input type="hidden" name="id" value={item.id} /><label><span>Status</span><select name="status" defaultValue={item.status}>{statuses.map((status) => <option key={status} value={status}>{status.replace("_", " ")}</option>)}</select></label><button className="secondary-button">Update</button></form></article>)}</div>}</section><aside className="workspace-panel intake-panel"><p className="eyebrow">NEW JOB</p><h2>Schedule work</h2><form action={createJob} className="record-form"><label>Job number<input name="jobNumber" placeholder="JOB-1001" required /></label><label>Accepted quote<select name="quoteId" defaultValue=""><option value="">Select a quote</option>{quotes.map((item) => <option key={item.id} value={item.id}>{item.quoteNumber} — {item.customerName || [item.firstName, item.lastName].filter(Boolean).join(" ") || "Customer"}</option>)}</select></label><div className="form-row"><label>Start<input name="scheduledStart" type="datetime-local" /></label><label>End<input name="scheduledEnd" type="datetime-local" /></label></div><div className="form-row"><label>Crew<input name="crewCount" type="number" min="0" defaultValue="2" /></label><label>Trucks<input name="truckCount" type="number" min="0" defaultValue="1" /></label></div><label>Origin<input name="originAddress" /></label><label>Destination<input name="destinationAddress" /></label><label>Dispatch notes<textarea name="dispatchNotes" rows={4} /></label><button className="primary-button">Schedule job</button></form></aside></div></>;
}
