"use client";

import { useMemo } from "react";

import { saveQuote } from "@/app/actions/quotes";
import { calculateQuoteCore } from "@/lib/pricing-core";

type QuoteValues = {
  id: string; moveDate: string; pricingModel: "local_hourly" | "long_haul" | "flat_rate"; tariffRule: "local_max_2018" | "section_3_long_haul" | "item_225_warehouse" | "manual"; originAddress: string; destinationAddress: string; fromCity: string; fromState: string; fromPostalCode: string; toCity: string; toState: string; toPostalCode: string; hours: number; foremen: number; movers: number; trucks: number; equipment: number; weight: number; tripMiles: number; hourlyRate: number; tripRate: number; flatRate: number; discountPercent: number; surchargePercent: number; salesTaxPercent: number; taxExempt: boolean; overtime: boolean; overrideTripCharge: boolean; notes: string;
};

const money = (value: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(value);

export function QuoteEditor({ values, customerName }: { values: QuoteValues; customerName: string }) {
  const preview = useMemo(() => calculateQuoteCore({ ...values }), [values]);
  return <form action={saveQuote} className="quote-editor">
    <input type="hidden" name="id" value={values.id} />
    <section className="editor-card"><p className="eyebrow">QUOTE HEADER</p><h2>{customerName}</h2><div className="form-row"><label>Move date<input name="moveDate" type="date" defaultValue={values.moveDate} /></label><label>Pricing model<select name="pricingModel" defaultValue={values.pricingModel}><option value="local_hourly">Local hourly</option><option value="long_haul">Long-haul tariff</option><option value="flat_rate">Flat / binding price</option></select></label></div><div className="form-row"><label>Tariff rule<select name="tariffRule" defaultValue={values.tariffRule}><option value="local_max_2018">Texas local maximum / 2018</option><option value="section_3_long_haul">Section 3 distance × weight</option><option value="item_225_warehouse">Item 225 warehouse service</option><option value="manual">Manual / contracted</option></select></label><label>Sales tax %<input name="salesTaxPercent" type="number" step="0.001" min="0" defaultValue={values.salesTaxPercent} /></label></div></section>
    <section className="editor-card"><p className="eyebrow">MOVE DETAILS</p><div className="form-row"><label>Origin address<input name="originAddress" defaultValue={values.originAddress} /></label><label>Destination address<input name="destinationAddress" defaultValue={values.destinationAddress} /></label></div><div className="form-row"><label>Origin city<input name="fromCity" defaultValue={values.fromCity} /></label><label>Origin state<input name="fromState" defaultValue={values.fromState} /></label><label>Origin ZIP<input name="fromPostalCode" defaultValue={values.fromPostalCode} /></label></div><div className="form-row"><label>Destination city<input name="toCity" defaultValue={values.toCity} /></label><label>Destination state<input name="toState" defaultValue={values.toState} /></label><label>Destination ZIP<input name="toPostalCode" defaultValue={values.toPostalCode} /></label></div></section>
    <section className="editor-card"><p className="eyebrow">LABOR &amp; TARIFF INPUTS</p><div className="form-row"><label>Estimated hours<input name="hours" type="number" step="0.25" min="0" defaultValue={values.hours} /></label><label>Foremen<input name="foremen" type="number" step="1" min="0" defaultValue={values.foremen} /></label><label>Movers<input name="movers" type="number" step="1" min="0" defaultValue={values.movers} /></label><label>Trucks<input name="trucks" type="number" step="1" min="0" defaultValue={values.trucks} /></label></div><div className="form-row"><label>Equipment units<input name="equipment" type="number" step="1" min="0" defaultValue={values.equipment} /></label><label>Weight (lbs)<input name="weight" type="number" step="1" min="0" defaultValue={values.weight} /></label><label>Trip miles<input name="tripMiles" type="number" step="1" min="0" defaultValue={values.tripMiles} /></label><label>Hourly override<input name="hourlyRate" type="number" step="0.01" min="0" defaultValue={values.hourlyRate} /></label></div><div className="form-row"><label>Trip rate / mile<input name="tripRate" type="number" step="0.01" min="0" defaultValue={values.tripRate} /></label><label>Flat/manual amount<input name="flatRate" type="number" step="0.01" min="0" defaultValue={values.flatRate} /></label><label>Discount %<input name="discountPercent" type="number" step="0.001" min="0" defaultValue={values.discountPercent} /></label><label>Surcharge %<input name="surchargePercent" type="number" step="0.001" min="0" defaultValue={values.surchargePercent} /></label></div><div className="check-row"><label><input name="overtime" type="checkbox" defaultChecked={values.overtime} /> Overtime</label><label><input name="taxExempt" type="checkbox" defaultChecked={values.taxExempt} /> Tax exempt</label><label><input name="overrideTripCharge" type="checkbox" defaultChecked={values.overrideTripCharge} /> Override trip charge</label></div></section>
    <section className="editor-card"><p className="eyebrow">NOTES</p><textarea name="notes" rows={5} defaultValue={values.notes} /><div className="quote-total"><span>Live local preview</span><strong>{money(preview.total)}</strong><small>{preview.warnings.join(" ") || "Calculated with Item 22 quarter-hour rounding and the selected tariff rule."}</small></div><button className="primary-button">Save and recalculate quote</button></section>
  </form>;
}
